---

- name: Installations
  include_tasks: setup.yml

- name: Goloop
  include_tasks: goloop.yml
  when: goloop_install | bool 

- name: UFW rules
  include_tasks: ufw.yml

- name: Include nginx conf files
  include_tasks: nginx.yml

- name: Application
  include_tasks: app.yml

- name: Configure cron jobs
  include_tasks: cron.yml
  when: cron_updater | bool

#
# Start application
#
#- name: Start node application via docker-compose
#  args:
#    chdir: "/home/{{ admin_user }}"
#  shell: docker-compose -f docker-compose.yml up -d
#
#- name: Wait for port 9080 to become open on the host, don't start checking for 10 seconds
#  wait_for:
#    port: 9080
#    delay: 10
